/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalbus;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import static rentalbus.TransaksiPeminjaman_Kasir.DATE_FORMAT_NOW;

/**
 *
 * @author Sylvia Putri
 */
public class Dashboard_Admin extends javax.swing.JFrame {
    KoneksiDB kon = new KoneksiDB();
    private String dateNow="";
    private String monthNow="";
    
    public Dashboard_Admin() throws SQLException {
        initComponents();
        dateNow = getDateNow();
        monthNow= getMonthNow();
        lblTransDay.setText(String.valueOf(setLblTransDay()));
        lblTransMonth.setText(String.valueOf(setLblTransMonth()));
        lblProfitDay.setText("Rp " + String.valueOf(setLblProfitDay()));
        lblProfitMonth.setText("Rp " + String.valueOf(setLblProfitMonth()));
        updateBusPopuler();
    }
    
    public int setLblTransDay() throws SQLException{
        int total =0;
        kon.connect();
        kon.createQuery("select * from transaksi_peminjaman where tgl_transaksi ='"+dateNow+"'");
        while(kon.myRs.next()) total++;
        kon.createQuery("select * from transaksi_pengembalian where tgl_transaksi ='"+dateNow+"'");
        while(kon.myRs.next()) total++;
        kon.close();
        return total;
    }
    
    public int setLblTransMonth() throws SQLException{
        int total =0;
        kon.connect();
        kon.createQuery("select * from transaksi_peminjaman where month(tgl_transaksi) ='"+monthNow+"'");
        while(kon.myRs.next()) total++;
        kon.createQuery("select * from transaksi_pengembalian where month(tgl_transaksi) ='"+monthNow+"'");
        while(kon.myRs.next()) total++;
        kon.close();
        return total;
    }
    
    public int setLblProfitDay() throws SQLException{
        int profit=0;
        kon.connect();
        kon.createQuery("select total_harga from transaksi_peminjaman where tgl_transaksi ='"+dateNow+"'");
        while(kon.myRs.next()) profit+=kon.myRs.getInt("total_harga");
        kon.createQuery("SELECT sum(total_parkir)+sum(total_tol)+sum(total_bbm) AS pengeluaran FROM `cost`, detail_pengembalian, transaksi_pengembalian where transaksi_pengembalian.tgl_transaksi ='"+dateNow+"' AND cost.id_detail_pengembalian=detail_pengembalian.id_detail_pengembalian AND detail_pengembalian.id_pengembalian = transaksi_pengembalian.id_pengembalian");
        while(kon.myRs.next()) profit-=kon.myRs.getInt("pengeluaran");
        kon.close();
        return profit;
    }
    
    public int setLblProfitMonth() throws SQLException{
        int profit=0;
        kon.connect();
        kon.createQuery("select total_harga from transaksi_peminjaman where month(tgl_transaksi) ='"+monthNow+"'");
        while(kon.myRs.next()) profit+=kon.myRs.getInt("total_harga");
        kon.createQuery("SELECT sum(total_parkir)+sum(total_tol)+sum(total_bbm) AS pengeluaran FROM `cost`, detail_pengembalian, transaksi_pengembalian where month(transaksi_pengembalian.tgl_transaksi) ='"+monthNow+"' AND cost.id_detail_pengembalian=detail_pengembalian.id_detail_pengembalian AND detail_pengembalian.id_pengembalian = transaksi_pengembalian.id_pengembalian");
        while(kon.myRs.next()) profit-=kon.myRs.getInt("pengeluaran");
        kon.close();
        return profit;
    }
    
    public void updateBusPopuler() throws SQLException{
        kon.connect();
        kon.createQuery("select * from jenis_bus order by jumlah_disewa desc limit 3");
        int index=0;
        while(kon.myRs.next()){
            if(index==0){
                lblOne.setText(kon.myRs.getString("nama_jenis"));
                lblBanyakOne.setText("("+kon.myRs.getString("jumlah_disewa")+" kali)");
            }
            else if(index==1){
                lblTwo.setText(kon.myRs.getString("nama_jenis"));
                lblBanyakTwo.setText("("+kon.myRs.getString("jumlah_disewa")+" kali)");
            }
            else{
                lblThree.setText(kon.myRs.getString("nama_jenis"));
                lblBanyakThree.setText("("+kon.myRs.getString("jumlah_disewa")+" kali)");
            }
            index++;
        }
        kon.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTransDay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTransMonth = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblProfitDay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProfitMonth = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblOne = new javax.swing.JLabel();
        lblTwo = new javax.swing.JLabel();
        lblThree = new javax.swing.JLabel();
        lblBanyakOne = new javax.swing.JLabel();
        lblBanyakTwo = new javax.swing.JLabel();
        lblBanyakThree = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel1.setText("Dashboard");

        lblTransDay.setBackground(new java.awt.Color(204, 204, 255));
        lblTransDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransDay.setText("11");
        lblTransDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Total Transaksi Hari Ini");

        lblTransMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransMonth.setText("131");
        lblTransMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Total Transaksi Bulan Ini");

        lblProfitDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfitDay.setText("8.900.000");
        lblProfitDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Total Pendapatan Hari Ini");

        lblProfitMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfitMonth.setText("73.740.000");
        lblProfitMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Total Pendapatan Bulan Ini");

        jLabel2.setText("Bus Terpopuler");

        jLabel4.setText("1.");

        jLabel6.setText("2.");

        jLabel8.setText("3.");

        lblOne.setText("-");

        lblTwo.setText("-");

        lblThree.setText("-");

        lblBanyakOne.setText("(0 kali)");

        lblBanyakTwo.setText("(0 kali)");

        lblBanyakThree.setText("(0 kali)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTransDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTransMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblProfitDay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblProfitMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBanyakOne))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBanyakTwo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblThree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBanyakThree)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTransDay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTransMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfitDay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfitMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblOne)
                    .addComponent(lblBanyakOne))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTwo)
                    .addComponent(lblBanyakTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblThree)
                    .addComponent(lblBanyakThree))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.setVisible(false);
        new HomePage_Admin().setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    public String getDateNow(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(cal.getTime());
    }
    
    public String getMonthNow(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("MM");
        return sdf.format(cal.getTime());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard_Admin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard_Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBanyakOne;
    private javax.swing.JLabel lblBanyakThree;
    private javax.swing.JLabel lblBanyakTwo;
    private javax.swing.JLabel lblOne;
    private javax.swing.JLabel lblProfitDay;
    private javax.swing.JLabel lblProfitMonth;
    private javax.swing.JLabel lblThree;
    private javax.swing.JLabel lblTransDay;
    private javax.swing.JLabel lblTransMonth;
    private javax.swing.JLabel lblTwo;
    // End of variables declaration//GEN-END:variables
}
