/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalbus;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static rentalbus.DaftarBus_Kasir.nama;


/**
 *
 * @author Sylvia Putri
 */
public class TransaksiPeminjaman_Kasir extends javax.swing.JFrame {
    static String nama;
    KoneksiDB kon = new KoneksiDB();
    public static final String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss";
    public ArrayList<BusPinjam> busList= new ArrayList<>();

    /**
     * Creates new form TransaksiPeminjaman_Kasir
     */
    public TransaksiPeminjaman_Kasir(String nama) throws SQLException {
        initComponents();
        this.nama = nama;
        lblKasir.setText(nama);
        lblNoPeminjaman.setText(getNoTransaksi());
        lblDateNow.setText(getDateNow());
        lblTotalDibayar.setVisible(false);
        txtTotalDibayar.setVisible(false);
        lblHarusLebihBesar.setVisible(false);
        lblKtpHarusIsi.setVisible(false);
        lblDaftarBusHarusIsi.setVisible(false);
    }
    
    public String getNoTransaksi() throws SQLException{
       String noTransaksi = null;
       kon.connect();
       kon.createQuery("select id_peminjaman from transaksi_peminjaman ORDER BY id_peminjaman");
       while(kon.myRs.next()){
           noTransaksi = String.valueOf(kon.myRs.getInt("id_peminjaman")+1);
       }
       return noTransaksi;
    }
    
    public String getDateNow(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
        return sdf.format(cal.getTime());
    }
    
    //Tambah bus (dari halaman inputBusPinjam)
    public void addBusPinjam(BusPinjam busPinjam){
        for(int i=0;i<busList.size();i++){
            if(busList.get(i).getNopol().equals(busPinjam.getNopol())){
                busList.remove(i);
                break;
            }
        }
        busList.add(busPinjam);
        show_bus(busList);
    }
    
    //hapus bus (dari halaman inputBusPinjam)
    public void removeBusPinjam(String nopol){
        for(int i=0;i<busList.size();i++){
            if(busList.get(i).getNopol().equals(nopol)){
                busList.remove(i);
                break;
            }
        }
        show_bus(busList);
    }
    
    //Menampilkan data BUS kedalam TABEL
    public void show_bus(ArrayList<BusPinjam> list){
        int total=0;
        DefaultTableModel model = (DefaultTableModel)tableBusPinjam.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getNopol();
            row[1] = list.get(i).getTgPinjam();
            row[2] = list.get(i).getTgKembali();
            row[3] = list.get(i).getJenisBus().getNamaJenis();
            row[4] = list.get(i).getNamaSupir();
            row[5] = list.get(i).getJenisBus().getHargaSewa();
            row[6] = list.get(i).getSubTotal();
            model.addRow(row);
            total+=list.get(i).getSubTotal();
        }
        lblTotal.setText(String.valueOf(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNoPeminjaman = new javax.swing.JLabel();
        lblKasir = new javax.swing.JLabel();
        lblDateNow = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKtpCust = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnTambahBus = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        radioAllInOne = new javax.swing.JRadioButton();
        lblTotalDibayar = new javax.swing.JLabel();
        txtTotalDibayar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBusPinjam = new javax.swing.JTable();
        lblHarusLebihBesar = new javax.swing.JLabel();
        lblKtpHarusIsi = new javax.swing.JLabel();
        lblDaftarBusHarusIsi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel1.setText("Transaksi Peminjaman");

        jLabel2.setText("No. Transaksi");

        jLabel3.setText("Kasir");

        jLabel4.setText("Tanggal & waktu");

        lblNoPeminjaman.setText("8323487");

        lblKasir.setText("Regina");

        lblDateNow.setText("14-10-2018 12:23:02");

        jLabel9.setText("No KTP Peminjam");

        jLabel10.setText("Daftar bus yang Dipinjam");

        btnTambahBus.setText("Tambah Bus");
        btnTambahBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahBusMouseClicked(evt);
            }
        });

        btnSelesai.setText("Selesai");
        btnSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseClicked(evt);
            }
        });

        jLabel28.setText("TOTAL (Rp)");

        lblTotal.setText("0");

        radioAllInOne.setLabel("All in One");
        radioAllInOne.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioAllInOneStateChanged(evt);
            }
        });

        lblTotalDibayar.setText("Total dibayar");

        jScrollPane2.setBorder(null);

        tableBusPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nopol", "Tg Pinjam", "Tg Harus Kembali", "Jenis Bus", "Sopir", "Harga Sewa/hari", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBusPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBusPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBusPinjam);

        lblHarusLebihBesar.setForeground(new java.awt.Color(204, 0, 0));
        lblHarusLebihBesar.setText("Harus lebih besar daripada total biaya sewa");

        lblKtpHarusIsi.setForeground(new java.awt.Color(204, 0, 0));
        lblKtpHarusIsi.setText("No KTP harus diisi");

        lblDaftarBusHarusIsi.setForeground(new java.awt.Color(204, 0, 0));
        lblDaftarBusHarusIsi.setText("Tidak ada bus yang dipinjam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1))
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTambahBus)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDaftarBusHarusIsi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblDateNow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblNoPeminjaman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblKasir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtKtpCust, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(lblKtpHarusIsi))))))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(radioAllInOne)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHarusLebihBesar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotalDibayar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotalDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelesai))))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNoPeminjaman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDateNow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKtpCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKtpHarusIsi)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnTambahBus)
                    .addComponent(lblDaftarBusHarusIsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAllInOne, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalDibayar)
                    .addComponent(txtTotalDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarusLebihBesar)
                .addGap(2, 2, 2)
                .addComponent(btnSelesai)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //tombol BACK
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.setVisible(false);
        new HomePage_Kasir(nama).setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnTambahBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBusMouseClicked
        new InputBusPinjam_Kasir(this).setVisible(true);
    }//GEN-LAST:event_btnTambahBusMouseClicked

    private void radioAllInOneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioAllInOneStateChanged
        if(!radioAllInOne.isSelected()){
            lblTotalDibayar.setVisible(false);
            txtTotalDibayar.setVisible(false);
        }
        else{
            lblTotalDibayar.setVisible(true);
            txtTotalDibayar.setVisible(true);
        }
    }//GEN-LAST:event_radioAllInOneStateChanged

    //kalau data di tabel diklik
    private void tableBusPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBusPinjamMouseClicked
        int index = tableBusPinjam.getSelectedRow();
        TableModel model = tableBusPinjam.getModel();
        String nopol = model.getValueAt(index, 0).toString();
        BusPinjam busPinjam = null;
        for(int i=0;i<busList.size();i++){
            if(busList.get(i).getNopol().equals(nopol)){
                busPinjam=busList.get(i);
                break;
            }
        }
        InputBusPinjam_Kasir inputBusPinjam = new InputBusPinjam_Kasir(this);
        inputBusPinjam.setVisible(true);
        inputBusPinjam.pack();
        inputBusPinjam.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inputBusPinjam.txtNopol.setText(busPinjam.getNopol());
        inputBusPinjam.txtPinjam.setText(busPinjam.getTgPinjam());
        inputBusPinjam.txtSampai.setText(busPinjam.getTgKembali());
    }//GEN-LAST:event_tableBusPinjamMouseClicked

    //button SELESAI diklik
    private void btnSelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseClicked
        int lulusCek=1;
        if(radioAllInOne.isSelected()){
            if(txtTotalDibayar.getText().toString().equals("")){
                lblHarusLebihBesar.setVisible(true);
                lulusCek=0;
            }
            else if(Integer.valueOf(txtTotalDibayar.getText().toString()) <= Integer.valueOf(lblTotal.getText().toString())){
                lblHarusLebihBesar.setVisible(true);
                lulusCek=0;
            }
            else lblHarusLebihBesar.setVisible(false);
        }
        if(txtKtpCust.getText().toString().equals("")){
            lblKtpHarusIsi.setVisible(true);
            lulusCek=0;
        }
        else lblKtpHarusIsi.setVisible(false);
        if(busList.isEmpty()){
            lblDaftarBusHarusIsi.setVisible(true);
            lulusCek=0;
        }
        else lblDaftarBusHarusIsi.setVisible(false);
        if(lulusCek==1){
            int id_kasir =0;
            try {
                kon.connect();
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                //cari id kasir
                kon.createQuery("Select id_kasir from kasir where nama_kasir='"+lblKasir.getText().toString()+"'");
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //set id kasir ke variabel id_kasir
                while(kon.myRs.next()){
                    id_kasir = kon.myRs.getInt("id_kasir");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }

            //dapatkan date now
            Calendar cal = Calendar.getInstance();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateNow = sdf.format(cal.getTime());
            //dapatkan id transaksi
            int idTrans = Integer.valueOf(lblNoPeminjaman.getText().toString());
            //dapatkan total pembayaran dan all in one
            int total;
            int allInOne;
            if(radioAllInOne.isSelected()){
                total = Integer.valueOf(txtTotalDibayar.getText().toString());
                allInOne = 1;
            }
            else{
                total = Integer.valueOf(lblTotal.getText().toString());
                allInOne = 0;
            }
            //dapatkan no ktp customer
            String noKtpCust = txtKtpCust.getText().toString();
            try {
                //masukkan ke tabel transaksi_peminjaman
                kon.createInsert("INSERT INTO `transaksi_peminjaman` VALUES ("+idTrans+", '"+dateNow+"', "+id_kasir+", "+total+", "+allInOne+", '"+noKtpCust+"')");
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }
            //masukkan ke tabel detail_peminjaman
            for(int i=0; i<busList.size();i++){
                try {
                    kon.createInsert("INSERT INTO `detail_peminjaman` VALUES (NULL, "+idTrans+", '"+busList.get(i).getNopol()+"', '"+busList.get(i).getTgPinjam()+"', '"+busList.get(i).getTgKembali()+"', "+busList.get(i).getSubTotal()+")");
                    int jumlahSewa = busList.get(i).getJenisBus().getJumlahDisewa() + 1;
                    String id_jenis = busList.get(i).getJenisBus().getIdJenis();
                    kon.createUpdate("UPDATE `jenis_bus` SET `jumlah_disewa` = "+jumlahSewa+" WHERE `jenis_bus`.`id_jenis` = '"+id_jenis+"'");
                    kon.createInsert("INSERT INTO `bookingbus` VALUES (NULL, '"+busList.get(i).getNopol()+"', '"+busList.get(i).getTgPinjam()+"', '"+busList.get(i).getTgKembali()+"');");
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //tambahan cek langsung
            for(int i=0; i<busList.size(); i++){
                try {
                    kon.createQuery("select * from bookingbus where nopol='"+busList.get(i).getNopol()+"' AND tgl_sewa<= '" + dateNow +"'");
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    //kalau ada, set status jadi "dipinjam"
                    if(kon.myRs.next()){
                        kon.createUpdate("UPDATE `bus` SET `status_sewa` = 'dipinjam' WHERE `bus`.`nopol_bus` = '"+busList.get(i).getNopol()+"' ");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //--------
            try {
                kon.close();
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }
            //balik ke homepage lagi
            this.setVisible(false);
            new HomePage_Kasir(nama).setVisible(true);
            JOptionPane.showMessageDialog(null, "Transaksi berhasil", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSelesaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransaksiPeminjaman_Kasir(nama).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPeminjaman_Kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambahBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDaftarBusHarusIsi;
    private javax.swing.JLabel lblDateNow;
    private javax.swing.JLabel lblHarusLebihBesar;
    private javax.swing.JLabel lblKasir;
    private javax.swing.JLabel lblKtpHarusIsi;
    private javax.swing.JLabel lblNoPeminjaman;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDibayar;
    private javax.swing.JRadioButton radioAllInOne;
    private javax.swing.JTable tableBusPinjam;
    private javax.swing.JTextField txtKtpCust;
    private javax.swing.JTextField txtTotalDibayar;
    // End of variables declaration//GEN-END:variables
}
